// Sample people for the matching screens (profiles/matches tables are empty until seed profiles land).
// Every person here is synthetic. Match % (s) is a stub for the deterministic scoring engine's output; the UI only displays it.
export const ME = { id: 'you', i: 'KP', n: 'Kien' };
const B = (vals, them) => [['Bedtime', 'moon', '23:00–00:00'], ['Wake time', 'sunrise', '07:00–08:00'], ['Cleaning', 'spray-can', '2×/week'], ['Guests', 'users', '1–2/month'], ['Noise', 'volume-2', 'quiet weekdays'], ['Smoking', 'cigarette', 'never']].map(([l, ic, y], i) => [l, ic, vals[i], y, them[i]]);
export const QUEUE = [
  { id: 'sam', i: 'SK', n: 'Sam', s: 87, meta: 'Astoria or Bushwick · $1,500–2,000 · Move-in Oct', bars: B([92, 88, 95, 64, 78, 100], ['22:00–23:00', '06:30–07:30', '2×/week', '1–2/month', 'music while cooking', 'never']), sum: 'Early-to-bed, cooks most nights, likes a quiet weekday apartment and a social Sunday.', click: ['Same bedtime window', 'Both clean 2×/week', 'Both never smoke'], clash: ['Noise: quiet weekdays vs music while cooking', 'Wake time 30 min apart'], aiClick: ['Same bedtime window', 'Both clean twice a week', 'Both cook at home'], aiClash: ['Sunday brunch guests', 'Music while cooking'], flag: true, saved: [['astoria', '2 BR · Astoria', '$1,725 / room', 'Apartment: Astoria living room'], ['bushwick', '2 BR · Bushwick', '[$1,650] / room', 'Apartment: Bushwick kitchen']] },
  { id: 'jordan', i: 'JT', n: 'Jordan', s: 84, meta: 'Ridgewood · $1,400–1,800 · Move-in Nov', bars: B([86, 80, 90, 72, 88, 100], ['23:30–00:30', '07:30–08:30', '2×/week', 'about 1/month', 'quiet weekdays', 'never']), sum: 'Works from home, keeps a tidy kitchen, goes out on weekends.', click: ['Same noise level', 'Both clean 2×/week', 'Both never smoke'], clash: ['Bedtime 30 min later', 'Works from home'], saved: [['ridgewood', '2 BR · Ridgewood', '$1,550 / room', 'Apartment: Ridgewood bedroom']] },
  { id: 'morgan', i: 'MB', n: 'Morgan', s: 82, meta: 'Bushwick · $1,600–2,100 · Move-in Oct', bars: B([78, 92, 84, 80, 70, 100], ['00:00–01:00', '07:00–08:00', '1×/week', '1–2/month', 'music some evenings', 'never']), sum: 'Early gym routine, cooks on Sundays, hosts a friend or two a month.', click: ['Same wake time', 'Same guest range', 'Both never smoke'], clash: ['Cleans once a week', 'Music some evenings'], saved: [['bushwick2', '3 BR · Bushwick', '$1,480 / room', 'Apartment: Bushwick living room']] },
  { id: 'taylor', i: 'TL', n: 'Taylor', s: 80, meta: 'Astoria · $1,500–1,900 · Move-in Dec', bars: B([90, 74, 88, 58, 82, 100], ['23:00–00:00', '08:30–09:30', '2×/week', '2–3/month', 'quiet weekdays', 'never']), sum: 'Night-shift nurse twice a week, quiet at home, has family visit often.', click: ['Same bedtime window', 'Both clean 2×/week', 'Same noise level'], clash: ['Guests 2–3/month', 'Wake time 90 min later'], saved: [['astoria2', '2 BR · Astoria', '$1,690 / room', 'Apartment: Astoria kitchen']] },
];
export const SHORT = [['AR', 'Alex'], ['RM', 'Robin'], ['CJ', 'Casey']];
export const PEOPLE = [['SK', 'Sam'], ['AR', 'Alex'], ['RM', 'Robin'], ['CJ', 'Casey'], ['JT', 'Jordan'], ['MB', 'Morgan'], ['TL', 'Taylor'], ['RD', 'Riley'], ['QN', 'Quinn'], ['AV', 'Avery'], ['DP', 'Drew'], ['SH', 'Sky'], ['EW', 'Emery'], ['PF', 'Parker'], ['RG', 'Reese'], ['BC', 'Blake'], ['KO', 'Kai'], ['JL', 'Jamie'], ['LS', 'Logan'], ['HM', 'Harper']];
export const TAGS = [['Early riser', 'Cooks daily', 'Quiet weekdays'], ['Night owl', 'Tidy kitchen', 'Rare guests'], ['Clean 2×/week', 'Early riser', 'No smoking'], ['Quiet weekdays', 'Cooks daily', 'Rare guests'], ['Night owl', 'Music at home', 'Clean 2×/week']];
// Match % per PEOPLE entry (same order, ranked high → low). Stub for the scoring engine; QUEUE people keep their `s`.
export const SCORES = [87, 86, 85, 85, 84, 82, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67];
export const REASONS = ['Same bedtime window, both clean 2×/week', 'Same guest range, both never smoke', 'Wake times within 30 min', 'Both clean 2×/week, same noise level', 'Same bedtime window, same guest range'];
// The demo pair used by /matches/[id], /agreement/[matchId] and /locked/[matchId].
export const personById = id => QUEUE.find(p => p.id === id) || QUEUE[0];
