// Every word and number in the video lives here. No imports, so Node scripts (gen-vo, check) can load it too.
// Copy rules (SPEC NFR-2/3): no em or en dashes anywhere; ranges use a hyphen or "to". Sentence case, no "!".
// Data is copied from the app, not imported: web/lib/score.ts (QUESTIONS) and the Kien/Sam pair pinned by web/lib/score.check.ts.

// Voiceover: one continuous ElevenLabs read. One line per scene, in order.
export const LINES = [
  {id: 'S01', vo: 'Every New Yorker has a roommate horror story.'},
  {id: 'S02', vo: 'Most start with one DM vibe check and a twelve-month lease.'},
  {id: 'S03', vo: 'RoomMe matches you on how you actually live.'},
  {id: 'S04', vo: 'Tap ten habits. Then talk for ninety seconds.'},
  {id: 'S05', vo: "We flag answers that don't add up."},
  {id: 'S06', vo: 'Your match score is a metric built from your answers.'},
  {id: 'S07', vo: "Shortlist up to five. Meet when it's mutual."},
  {id: 'S08', vo: 'Every listing gets a fair-price check.'},
  {id: 'S09', vo: 'Agree on house rules, then apply together.'},
  {id: 'S10', vo: 'RoomMe. Find a roommate who lives like you do.'},
] as const;

export type SceneId = (typeof LINES)[number]['id'];

// Sound effects generated by scripts/gen-sfx.ts into public/audio/sfx/<name>.mp3. Scenes place them with <Sfx name=... />.
export const SFX = {
  whoosh: 'fast airy whoosh, cinematic transition, clean, no reverb tail',
  'whoosh-soft': 'soft short swish, subtle UI transition',
  tap: 'crisp soft UI tap click on glass, single',
  pop: 'small soft bubble pop, message notification, single',
  type: 'quiet fast keyboard typing, 1 second, laptop keys',
  riser: 'short tension riser building up, cinematic, 1.5 seconds, ends abruptly',
  impact: 'deep cinematic impact boom with short airy tail, logo reveal',
  stamp: 'rubber stamp thud on paper desk, single hit',
  chime: 'bright clean positive UI chime, two notes, success',
  paper: 'paper sheet slide and flip, quick',
} as const;
export type SfxName = keyof typeof SFX;

// Landing page problem cards (web/app/LandingScreen.jsx): habit tag + the horror it causes.
export const HORROR = [
  {tag: 'Sleep', icon: 'moon', line: 'Their 6 a.m. alarm, your 2 a.m. bedtime.'},
  {tag: 'Dishes', icon: 'utensils', line: 'The sink that’s never empty.'},
  {tag: 'Guests', icon: 'users', line: 'The partner who quietly moved in.'},
  {tag: 'Noise', icon: 'volume-2', line: 'Calls on speaker at midnight.'},
] as const;

// S02: how it goes today. The DMs are illustrative.
export const PROBLEM = {
  dms: [
    {from: 'them', text: 'is the room still open?'},
    {from: 'you', text: 'yes. are you chill?'},
    {from: 'them', text: 'super chill lol'},
  ],
  dmLabel: 'One DM vibe check.',
  leaseLabel: '12-month lease.',
  lease: {title: 'Residential lease', term: 'Term: 12 months', sign: 'Tenant signature'},
} as const;

// S03: the reveal lockup.
export const REVEAL = {line: 'Matched on habits. Checked before the lease.', habits: HORROR.map((h) => ({tag: h.tag, icon: h.icon}))} as const;

export const STAT = {vacancy: '1.41%', note: 'Lowest since 1968', source: 'NYC HPD'} as const;

// The demo pair from the landing page and score.check.ts: Kien vs Sam, 87%.
export const PAIR = {
  you: {name: 'Kien', initials: 'KP'},
  them: {name: 'Sam', initials: 'SK', meta: 'Astoria or Bushwick · $1,500-2,000 · Move-in Oct'},
  pct: 87,
  exact: 87.4,
  tagsThem: ['Early riser', 'Rare guests', 'Works from home'],
  click: ['Same bedtime window', 'Clean equally often', 'Same dishes timing'],
  clash: ['Work from home: 1-2 days vs 3-4 days', 'Overnight guests: 1-2 nights a month vs About once a week'],
} as const;

// The ten per-habit agreements (the bars). Sum 874 / 10 = 87.4 -> 87%.
export const PARTS = [
  {label: 'Bedtime', icon: 'moon', v: 100, you: '23:00-00:00', them: '23:00-00:00'},
  {label: 'Wake time', icon: 'sunrise', v: 75, you: '07:00-08:00', them: '06:00-07:00'},
  {label: 'Cleaning', icon: 'spray-can', v: 100, you: '2/week', them: '2/week'},
  {label: 'Dishes', icon: 'utensils', v: 100, you: 'The same day', them: 'The same day'},
  {label: 'Guests', icon: 'users', v: 100, you: '1-2/month', them: '1-2/month'},
  {label: 'Overnight guests', icon: 'house', v: 64, you: '1-2 nights a month', them: 'About once a week'},
  {label: 'Sleep noise', icon: 'bed-double', v: 100, you: 'No one’s mentioned it', them: 'No one’s mentioned it'},
  {label: 'Noise', icon: 'volume-2', v: 75, you: 'Quiet talking', them: 'Music or TV, low'},
  {label: 'Work from home', icon: 'coffee', v: 60, you: '1-2 days', them: '3-4 days'},
  {label: 'Smoking', icon: 'cigarette', v: 100, you: 'Never', them: 'Never'},
] as const;
// The live app calls the score "a metric" (web/app/LandingScreen.jsx, MatchScore caption).
export const SCORE = {note: 'ten answers, averaged', caption: 'match · metric'} as const;
export const FORMULA = '(100 + 75 + 100 + 100 + 100 + 64 + 100 + 75 + 60 + 100) ÷ 10 = 87.4';

// Quick-tap quiz (web/lib/score.ts QUESTIONS[0]); Kien taps option 2.
export const QUIZ = {
  step: '3 of 10',
  q: 'What time do you actually go to bed on weeknights?',
  opts: ['Before 22:00', '22:00-23:00', '23:00-00:00', '00:00-01:00', 'After 01:00'],
  pick: 2,
  label: '10 quick taps',
} as const;

// Voice interview screen (web/app/profile/VoiceScreens.jsx).
export const VOICE = {
  eyebrow: 'Voice interview · 90 seconds',
  title: 'Tell us how you actually live.',
  prompts: [
    'A perfect Sunday at home',
    'A roommate habit that drives you crazy',
    'How you bring up a problem',
    'Your typical weekday',
    'Social hub or quiet recharge?',
  ],
  timer: '1:30 left',
  status: 'Listening',
  transcript: 'Okay, a perfect Sunday. I sleep in. Then I usually have people over for brunch. Most Sundays it’s three or four friends and a big pan of eggs.',
  note: 'Audio isn’t stored. You’ll review the transcript before it’s saved.',
  label: '90-second voice interview',
} as const;

// Self-check contradiction (landing sample + review screen).
export const CONTRADICTION = {
  eyebrow: 'Worth a second look',
  answers: [
    {source: 'Quick-tap · Guests', quote: '1-2 a month'},
    {source: 'Voice interview', quote: 'I host brunch most Sundays.'},
  ],
  question: 'How many people come over in a typical month?',
  headline: 'We flag answers that don’t add up.',
} as const;

// Matches (web/lib/sample-data.js names, web/app/matches copy).
export const MATCHES = {
  title: 'Your top 20',
  sub: 'Ranked by your match score: a metric built from your answers.',
  names: ['Sam', 'Jordan', 'Morgan', 'Taylor', 'Alex', 'Robin', 'Casey', 'Riley', 'Quinn', 'Avery', 'Drew', 'Sky', 'Emery', 'Parker', 'Reese', 'Blake', 'Kai', 'Jamie', 'Logan', 'Harper'],
  shortlist: 'Shortlist 2 / 5',
  mutualRule: 'Meetups open only when it’s mutual.',
  mutual: 'It’s mutual',
  mutualSub: 'You and Sam both said yes.',
  meetup: 'Meet before you sign.',
} as const;

// Listings: live Tiger Data numbers (Sep 26-27 pull) and a real fair-price Astoria 2 BR (its trust check shows the 2 BR median).
export const LISTINGS = {
  title: 'Places worth splitting.',
  count: '1,380 listings',
  areas: '24 neighborhoods',
  example: {address: '3314 31st Ave APT 2F', area: 'Astoria', beds: '2 BR', rent: '$2,500/mo', perRoom: '$1,250 / room', median: 'Astoria median ≈$1,998'},
  badges: ['Fair price', 'Above median', 'Check before paying'],
  headline: '1,380 listings. 24 neighborhoods.',
} as const;

// House Agreement (web/app/agreement/[matchId]/AgreementScreen.jsx), rules drafted from Kien's and Sam's answers.
export const AGREEMENT = {
  eyebrow: 'House agreement · Draft',
  title: 'Sam & Kien · 2 BR Astoria',
  sub: 'Drafted from both profiles. Edit anything.',
  rules: [
    {icon: 'moon', label: 'Quiet hours', text: 'Weeknights 22:00 to 08:00'},
    {icon: 'users', label: 'Guests', text: 'Up to 2 guests a month'},
    {icon: 'spray-can', label: 'Chores', text: 'Shared spaces twice a week. Dishes the same day.'},
    {icon: 'volume-2', label: 'Noise', text: 'Quiet talking on weeknights'},
    {icon: 'cigarette', label: 'Smoking', text: 'No smoking or cannabis at home'},
    {icon: 'wallet', label: 'Bills', text: 'Rent split 50/50 ($1,250 each)'},
  ],
  timeline: ['Matched', 'Meetup planned', 'Agreement', 'Lock listing', 'Apply on Zillow'],
  locked: 'Sam & Kien: go get the Astoria 2 BR.',
  cta: 'Apply on Zillow ↗',
  pdf: 'Download PDF',
  note: 'RoomMe isn’t a broker and doesn’t hold deposits.',
} as const;

export const END = {
  // Same words as the live hero H1, which the video flies into at the end.
  tagline: 'Find a roommate who lives like you do.',
  url: 'roomme.tech',
  event: 'DivHacks 2026 · Live Better',
  credits: 'Built with Tiger Data · ElevenLabs · Gemini · SearchApi',
} as const;
